/* Populate tabla regiones */


INSERT INTO regiones (nombre, id) VALUES('España',1);
INSERT INTO regiones (nombre, id) VALUES('Inglaterra',2);
INSERT INTO regiones (nombre, id) VALUES('Francia',3);
INSERT INTO regiones (nombre, id) VALUES('Holanda',4);
INSERT INTO regiones (nombre, id) VALUES('Noruega',5);
INSERT INTO regiones (nombre, id) VALUES('Suecia',6);
INSERT INTO regiones (nombre, id) VALUES('Portugal',7);
INSERT INTO regiones (nombre, id) VALUES('Dinamarca',8);
INSERT INTO regiones (nombre, id) VALUES('Italia',9);
INSERT INTO regiones (nombre, id) VALUES('Grecia',10);

INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',8);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',9);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',10);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',8);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',9);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',8);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05',1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06',3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01',5);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02',7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03',2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04',4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01',6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10',5);

